services:
  - type: web
    name: merchant-image-validator
    runtime: python
    plan: starter
    env: python
    pythonVersion: 3.12.7   # âœ… specify supported version
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: python run.py
    envVars:
      - key: OPENAI_API_KEY
        sync: false
        fromSecret: true
